from time import time as tt

start = tt()
print('Hello world0')
print('Hello world1')
print('Hello world2')
print('Hello world3')
print('Hello world4')
print('Hello world5')
print('Hello world6')
print('Hello world7')
print('Hello world8')
print('Hello world9')
print('Hello world10')
print('Hello world11')
print('Hello world12')
print('Hello world13')
print('Hello world14')
print('Hello world15')
print('Hello world16')
print('Hello world17')
print('Hello world18')
print('Hello world19')
print('Hello world20')
end = tt()
print(end - start, 'sec')